version: '3'

services:
  app:
    build: .
    command: bash -c "rm tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    env_file: .env.dev
    volumes:
    - .:/app
    ports:
    - "3000:3000"